### ISSUE TITLE
Fix README formatting

### ISSUE THREAD

**Issue by craicoverflow** [xNexeon/zForum#5]
In the README, the **Technologies Used** and **Libraries Used** sections do not have proper bullet points.

Eg:

## Technologies Used

-Javascript -HTML -CSS

Should look like this:

# Technologies Used

- Javascript
- HTML
- CSS

**Comment by craicoverflow** [comment]
Ping @xNexeon for your consideration.

**Comment by xNexeon** [comment]
Done

**Comment by craicoverflow** [comment]
> Done

:+1:
